version: '3'

services:
  redis:
    container_name: redis
    image: redislabs/rejson
    sysctls:
      - net.core.somaxconn=1024
    restart: always

  bot:
    ports:
      - "7000:7000"
      - "5858:5858"
    container_name: bot
    image: disctest
    depends_on:
      - redis
    build: .
    restart: always
